# Generated by Django 4.0.2 on 2022-05-21 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='background_img',
            field=models.CharField(max_length=800, null=True),
        ),
    ]
