# Generated by Django 4.0.2 on 2022-05-21 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0003_alter_profile_background_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_img',
            field=models.CharField(blank=True, default='', max_length=800),
        ),
    ]
