# Generated by Django 4.0.2 on 2022-05-29 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0004_alter_post_post_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='city',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_img',
            field=models.CharField(blank=True, default='', max_length=800),
        ),
        migrations.AlterField(
            model_name='profile',
            name='relationship',
            field=models.BooleanField(default=False),
        ),
    ]
